package lexer;

public enum TokenKind {

    PUBLIC, CLASS, STATIC, VOID, EXTENDS, IMPLEMENTS,

    DOT, COMMA, SEMICOLON, LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,

    STRING_LITERAL,

    IDENTIFIER, EOF
}
